language: python
python: 3.6
sudo: enabled
before_install:
- sudo apt-get update
- sudo apt-get install -y git
- sudo apt-get install -y curl
install: make install-dev
script: make build
after_success:
- codecov
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on: 
    branch: master
